# Traffic Data Merge

In [2]:
import pandas as pd
import numpy as np

In [72]:
traffic_data = pd.read_excel('Data/ny flow data.xlsx')

In [4]:
traffic_data.head()

,Unnamed: 0,ID,Segment ID,Roadway Name,From,To,Direction,Date,12:00-1:00 AM,1:00-2:00AM,...,9:00-10:00PM,10:00-11:00PM,11:00-12:00AM,Start Intersection,End Intersection,Lat Start,Lng Start,Lat End,Lng End,distance
0,0,2,70376,3 Avenue,East 154 Street,East 155 Street,NB,09/13/2014,204.0,177.0,...,328,282,240,3 Avenue East 154 Street,3 Avenue East 155 Street,40.818951,-73.914039,40.819544,-73.913528,0.048887
1,1,2,70376,3 Avenue,East 155 Street,East 154 Street,SB,09/13/2014,140.0,51.0,...,247,237,191,3 Avenue East 155 Street,3 Avenue East 154 Street,40.819544,-73.913528,40.818951,-73.914039,0.048887
2,2,56,176365,Bedford Park Boulevard,Grand Concourse,Valentine Avenue,EB,09/13/2014,94.0,73.0,...,183,147,103,Bedford Park Boulevard Grand Concourse,Bedford Park Boulevard Valentine Avenue,40.872153,-73.888070,40.871298,-73.887010,0.081017
3,3,56,176365,Bedford Park Boulevard,Grand Concourse,Valentine Avenue,WB,09/13/2014,88.0,82.0,...,162,157,103,Bedford Park Boulevard Grand Concourse,Bedford Park Boulevard Valentine Avenue,40.872153,-73.888070,40.871298,-73.887010,0.081017
4,4,62,147673,Broadway,West 242 Street,240 Street,SB,09/13/2014,255.0,209.0,...,465,425,324,Broadway West 242 Street,Broadway 240 Street,40.889463,-73.898357,40.886528,-73.899683,0.214140

In [5]:
traffic_data['Segment Address']=traffic_data.apply(lambda x: x['Roadway Name'] + '-' + x['From'] + '-' + x['To'], axis = 1)

In [6]:
traffic_data.columns

Index(['Unnamed: 0', 'ID', 'Segment ID', 'Roadway Name', 'From', 'To',
       'Direction', 'Date', '12:00-1:00 AM', '1:00-2:00AM', '2:00-3:00AM',
       '3:00-4:00AM', '4:00-5:00AM', '5:00-6:00AM', '6:00-7:00AM',
       '7:00-8:00AM', '8:00-9:00AM', '9:00-10:00AM', '10:00-11:00AM',
       '11:00-12:00PM', '12:00-1:00PM', '1:00-2:00PM', '2:00-3:00PM',
       '3:00-4:00PM', '4:00-5:00PM', '5:00-6:00PM', '6:00-7:00PM',
       '7:00-8:00PM', '8:00-9:00PM', '9:00-10:00PM', '10:00-11:00PM',
       '11:00-12:00AM', 'Start Intersection', 'End Intersection', 'Lat Start',
       'Lng Start', 'Lat End', 'Lng End', 'distance', 'Segment Address'],
      dtype='object')

In [7]:
columns_to_keep = ['ID', 'Segment ID', 'Roadway Name', 'From', 'To', 'Date', 'Start Intersection', 
                   'End Intersection', 'Lat Start', 'Lng Start', 'Lat End', 'Lng End', 'distance', 'Segment Address']

columns_to_average = ['12:00-1:00 AM', '1:00-2:00AM', '2:00-3:00AM', '3:00-4:00AM', '4:00-5:00AM', 
                      '5:00-6:00AM', '6:00-7:00AM', '7:00-8:00AM', '8:00-9:00AM', '9:00-10:00AM', 
                      '10:00-11:00AM', '11:00-12:00PM', '12:00-1:00PM', '1:00-2:00PM', '2:00-3:00PM',
                      '3:00-4:00PM', '4:00-5:00PM', '5:00-6:00PM', '6:00-7:00PM', '7:00-8:00PM', 
                      '8:00-9:00PM', '9:00-10:00PM', '10:00-11:00PM', '11:00-12:00AM']

In [8]:
traffic_data_out = traffic_data.groupby(by='Segment Address')[columns_to_average].mean()

In [9]:
traffic_data_out.reset_index(inplace = True)

In [10]:
traffic_data_out[columns_to_keep] = traffic_data[columns_to_keep]

In [11]:
traffic_data_out['Center Lat'] = traffic_data_out[['Lat Start','Lat End']].mean(axis=1)
traffic_data_out['Center Lng'] = traffic_data_out[['Lng Start','Lng End']].mean(axis=1)

In [12]:
traffic_data_out.head()

,Segment Address,12:00-1:00 AM,1:00-2:00AM,2:00-3:00AM,3:00-4:00AM,4:00-5:00AM,5:00-6:00AM,6:00-7:00AM,7:00-8:00AM,8:00-9:00AM,...,Date,Start Intersection,End Intersection,Lat Start,Lng Start,Lat End,Lng End,distance,Center Lat,Center Lng
0,3 Avenue-East 154 Street-East 155 Street,979.111111,726.777778,532.222222,443.444444,453.000000,688.333333,823.777778,1053.222222,1114.444444,...,09/13/2014,3 Avenue East 154 Street,3 Avenue East 155 Street,40.818951,-73.914039,40.819544,-73.913528,0.048887,40.819247,-73.913783
1,3 Avenue-East 155 Street-East 154 Street,679.000000,592.333333,534.666667,409.000000,320.666667,317.111111,414.888889,501.333333,524.777778,...,09/13/2014,3 Avenue East 155 Street,3 Avenue East 154 Street,40.819544,-73.913528,40.818951,-73.914039,0.048887,40.819247,-73.913783
2,Bedford Park Boulevard-Grand Concourse-Valenti...,867.000000,621.777778,483.000000,402.333333,458.888889,524.777778,717.222222,1246.444444,1376.777778,...,09/13/2014,Bedford Park Boulevard Grand Concourse,Bedford Park Boulevard Valentine Avenue,40.872153,-73.888070,40.871298,-73.887010,0.081017,40.871725,-73.887540
3,Bedford Park Boulevard-Grand Concourse-Valenti...,1331.555556,1061.555556,861.000000,670.888889,565.333333,578.444444,978.444444,1455.000000,1470.222222,...,09/13/2014,Bedford Park Boulevard Grand Concourse,Bedford Park Boulevard Valentine Avenue,40.872153,-73.888070,40.871298,-73.887010,0.081017,40.871725,-73.887540
4,Broadway-West 242 Street-240 Street,965.666667,815.777778,620.888889,508.444444,568.111111,725.111111,1209.666667,1415.888889,1435.666667,...,09/13/2014,Broadway West 242 Street,Broadway 240 Street,40.889463,-73.898357,40.886528,-73.899683,0.214140,40.887996,-73.899020

In [13]:
rows_with_nan = traffic_data_out.isnull().any(axis =1)
traffic_data_out = traffic_data_out[~rows_with_nan]

In [14]:
traffic_data_out.shape

(1705, 40)

In [15]:
import datetime

def seperate_month_date(df):
    
    month_list = []
    year_list = []
    weekday_list = [] 
    day_name = []
    
    date = df['Date']

    
    for row in list(date):
        datee = datetime.datetime.strptime(row, "%m/%d/%Y")
        day_name.append(datetime.datetime.strftime(datee, "%A"))

        year_list.append(datee.year)
        month_list.append(datee.month)
        weekday_list.append(datee.weekday())
    
    df['year'] = year_list
    df['month'] = month_list
    df['weekday'] = weekday_list
    df['day name']  = day_name
    
    return df

In [16]:
seperate_month_date(traffic_data_out)

,Segment Address,12:00-1:00 AM,1:00-2:00AM,2:00-3:00AM,3:00-4:00AM,4:00-5:00AM,5:00-6:00AM,6:00-7:00AM,7:00-8:00AM,8:00-9:00AM,...,Lng Start,Lat End,Lng End,distance,Center Lat,Center Lng,year,month,weekday,day name
0,3 Avenue-East 154 Street-East 155 Street,979.111111,726.777778,532.222222,443.444444,453.000000,688.333333,823.777778,1053.222222,1114.444444,...,-73.914039,40.819544,-73.913528,0.048887,40.819247,-73.913783,2014,9,5,Saturday
1,3 Avenue-East 155 Street-East 154 Street,679.000000,592.333333,534.666667,409.000000,320.666667,317.111111,414.888889,501.333333,524.777778,...,-73.913528,40.818951,-73.914039,0.048887,40.819247,-73.913783,2014,9,5,Saturday
2,Bedford Park Boulevard-Grand Concourse-Valenti...,867.000000,621.777778,483.000000,402.333333,458.888889,524.777778,717.222222,1246.444444,1376.777778,...,-73.888070,40.871298,-73.887010,0.081017,40.871725,-73.887540,2014,9,5,Saturday
3,Bedford Park Boulevard-Grand Concourse-Valenti...,1331.555556,1061.555556,861.000000,670.888889,565.333333,578.444444,978.444444,1455.000000,1470.222222,...,-73.888070,40.871298,-73.887010,0.081017,40.871725,-73.887540,2014,9,5,Saturday
4,Broadway-West 242 Street-240 Street,965.666667,815.777778,620.888889,508.444444,568.111111,725.111111,1209.666667,1415.888889,1435.666667,...,-73.898357,40.886528,-73.899683,0.214140,40.887996,-73.899020,2014,9,5,Saturday
5,Broadway-West 242 Street-240 Street,663.666667,613.222222,465.777778,400.222222,373.777778,396.888889,448.444444,611.222222,813.555556,...,-73.898357,40.886528,-73.899683,0.214140,40.887996,-73.899020,2014,9,5,Saturday
6,Broadway-West 242 Street-240 Street,1044.333333,795.222222,621.111111,482.222222,436.555556,468.555556,804.666667,1231.888889,1197.333333,...,-73.898357,40.886528,-73.899683,0.214140,40.887996,-73.899020,2014,9,5,Saturday
7,Bronx River Parkway-Bronx River-East Gun Hill ...,595.222222,420.333333,332.888889,301.777778,340.777778,407.333333,627.000000,1032.444444,1127.777778,...,-73.834548,40.876960,-73.869180,5.204881,40.912312,-73.851864,2014,9,5,Saturday
8,Bronx River Parkway-East Gun Hill Road-Bronx R...,1122.777778,1027.888889,865.444444,658.666667,490.555556,489.111111,724.444444,906.777778,929.666667,...,-73.869180,40.947664,-73.834548,5.204881,40.912312,-73.851864,2014,9,5,Saturday
9,Brook Avenue-East 152 Street-East 153 Street,1261.444444,1050.444444,806.111111,633.111111,512.777778,552.000000,944.666667,1295.888889,1308.000000,...,-73.914036,40.818013,-73.913217,0.107710,40.817297,-73.913626,2014,9,5,Saturday
10,East 138 Street-Canal Place-Rider Avenue,1221.222222,1066.000000,837.333333,650.888889,541.555556,416.111111,488.111111,885.000000,1183.333333,...,-73.928547,40.811740,-73.928134,0.030244,40.811893,-73.928341,2014,9,5,Saturday
11,East 138 Street-Rider Avenue-Canal Place,488.111111,384.666667,289.555556,245.000000,315.777778,436.444444,684.888889,1054.666667,1175.777778,...,-73.928134,40.812046,-73.928547,0.030244,40.811893,-73.928341,2014,9,5,Saturday
12,Concourse Village West-East 156 Street-East 15...,543.333333,394.555556,294.111111,282.666667,329.000000,376.777778,633.555556,886.444444,876.333333,...,-73.923075,40.823626,-73.923075,0.000000,40.823626,-73.923075,2014,9,5,Saturday
13,Courtladt Avenue-East 153 Street-East 154 Street,38.388889,20.722222,16.000000,13.166667,15.055556,23.000000,63.833333,157.722222,176.500000,...,-73.918284,40.819998,-73.918005,0.045608,40.819685,-73.918145,2014,9,5,Saturday
14,East 144 Street-A J Griffin Place-Grand Concourse,1144.444444,971.444444,744.000000,645.000000,543.222222,476.888889,436.666667,600.666667,780.888889,...,-73.918391,40.816561,-73.928281,0.600273,40.814369,-73.923336,2014,9,5,Saturday
15,East 144 Street-Grand Concourse-A J Griffin Place,1897.666667,1491.222222,1100.444444,966.333333,886.777778,1055.555556,1456.777778,1703.666667,1737.222222,...,-73.928281,40.812178,-73.918391,0.600273,40.814369,-73.923336,2014,9,5,Saturday
16,East 149 Street-A J Griffin Place-Grand Concourse,32.166667,21.555556,16.555556,13.222222,16.055556,23.722222,71.000000,152.666667,165.388889,...,-73.914883,40.818597,-73.927234,0.695564,40.816756,-73.921058,2014,9,5,Saturday
17,East 149 Street-Grand Concourse-A J Griffin Place,793.000000,586.666667,499.222222,409.333333,340.888889,309.222222,480.000000,705.111111,897.555556,...,-73.927234,40.814915,-73.914883,0.695564,40.816756,-73.921058,2014,9,5,Saturday
18,East 149 Street-Morris Avenue-Park Avenue,1484.777778,1108.777778,901.888889,749.111111,701.000000,846.666667,1249.555556,1498.555556,1726.222222,...,-73.922783,40.818059,-73.925169,0.134188,40.817707,-73.923976,2014,9,5,Saturday
19,East 149 Street-Park Avenue-Morris Avenue,1077.222222,793.555556,652.000000,560.222222,576.666667,760.888889,1038.111111,1275.666667,1328.000000,...,-73.925169,40.817355,-73.922783,0.134188,40.817707,-73.923976,2014,9,5,Saturday
20,Eastchester Road-East Gun Hill Road-Adee Avenue,56.333333,43.222222,29.444444,27.888889,33.944444,51.611111,105.333333,230.944444,202.888889,...,-73.841836,40.869427,-73.842639,0.095673,40.868804,-73.842238,2014,9,5,Saturday
21,Eastchester Road-East Gun Hill Road-Adee Avenue,41.444444,26.388889,19.666667,16.722222,22.666667,44.666667,113.777778,212.388889,205.666667,...,-73.841836,40.869427,-73.842639,0.095673,40.868804,-73.842238,2014,9,5,Saturday
22,Eastchester Road-Givan Avenue-Tillotson Avenue,72.222222,55.388889,47.944444,40.111111,54.444444,56.000000,85.055556,131.277778,130.944444,...,-73.845106,40.876378,-73.846027,0.124663,40.875545,-73.845567,2014,9,5,Saturday
23,Eastchester Road-Givan Avenue-Tillotson Avenue,163.250000,100.000000,65.722222,48.111111,54.027778,86.611111,188.611111,344.916667,418.194444,...,-73.845106,40.876378,-73.846027,0.124663,40.875545,-73.845567,2014,9,5,Saturday
24,East 233 Street-Webster Avenue-Bronx River Par...,122.333333,82.000000,55.166667,38.722222,46.277778,73.777778,155.888889,291.888889,343.388889,...,-73.863550,40.886753,-73.838231,1.453504,40.891069,-73.850890,2014,9,5,Saturday
25,East 233 Street-Webster Avenue-Bronx River Par...,105.500000,75.555556,59.194444,53.916667,61.972222,73.138889,125.611111,182.750000,201.861111,...,-73.863550,40.886753,-73.838231,1.453504,40.891069,-73.850890,2014,9,5,Saturday
26,East Fordham Road-Southern Boulevard-Bronx Riv...,772.333333,606.222222,509.888889,399.444444,369.555556,435.555556,671.888889,792.777778,880.000000,...,-73.880799,40.862038,-73.896960,0.919518,40.859439,-73.888880,2014,9,5,Saturday
27,East Fordham Road-Southern Boulevard-Bronx Riv...,450.722222,342.388889,239.222222,218.333333,178.944444,222.166667,307.555556,425.055556,536.166667,...,-73.880799,40.862038,-73.896960,0.919518,40.859439,-73.888880,2014,9,5,Saturday
28,East Mosholu Parkway-Grand Concourse-Van Court...,351.818182,272.363636,160.000000,166.727273,144.000000,201.636364,359.818182,511.090909,668.636364,...,-73.884157,40.876475,-73.883191,0.162984,40.877598,-73.883674,2014,9,5,Saturday
29,East Tremont Avenue-Anthony Avenue-Monroe Avenue,602.111111,416.555556,334.555556,281.111111,247.111111,316.777778,522.333333,743.222222,970.000000,...,-73.903285,40.849281,-73.905727,0.133671,40.849001,-73.904506,2014,9,5,Saturday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,West 181 Street-St. Nicholas Avenue-Wadsworth ...,43.555556,31.111111,21.555556,17.444444,20.777778,30.111111,56.000000,103.666667,133.000000,...,-73.933755,40.849827,-73.934984,0.074088,40.849561,-73.934370,2014,9,6,Sunday
1678,West 181 Street-Wadsworth Avenue-St. Nicholas ...,108.055556,79.611111,62.555556,54.444444,54.277778,62.333333,108.055556,221.000000,253.333333,...,-73.934984,40.849296,-73.933755,0.074088,40.849561,-73.934370,2014,9,6,Sunday
1679,West 116 Street-Lenox Avenue-Adam C Powell Bou...,270.833333,205.888889,168.055556,134.944444,161.500000,183.944444,287.555556,490.222222,547.055556,...,-73.949623,40.803203,-73.952450,0.169549,40.802606,-73.951036,2014,9,6,Sunday
1680,West 116 Street-Lenox Avenue-Adam C Powell Bou...,240.250000,189.208333,142.916667,118.250000,148.583333,188.250000,327.625000,544.458333,571.333333,...,-73.949623,40.803203,-73.952450,0.169549,40.802606,-73.951036,2014,9,6,Sunday
1681,West 145 Street-St. Nicholas Avenue-Edgecomb A...,79.666667,53.222222,41.444444,32.111111,46.111111,78.666667,131.777778,220.555556,270.111111,...,-73.944716,40.823660,-73.943839,0.052304,40.823841,-73.944277,2014,9,6,Sunday
1682,West 145 Street-Edgecomb Avenue-St. Nicholas A...,216.194444,172.472222,137.416667,113.222222,105.777778,122.277778,166.777778,250.500000,295.750000,...,-73.943839,40.824022,-73.944716,0.052304,40.823841,-73.944277,2014,9,6,Sunday
1683,West Farms Road-Cross Bronx Expressway-174 Street,129.888889,95.444444,76.555556,76.388889,76.555556,100.388889,163.944444,232.277778,251.333333,...,-73.881600,40.837445,-73.887809,0.506023,40.840253,-73.884705,2014,9,6,Sunday
1686,Westchester Avenue-East 167 Avenue-Home Street,876.333333,601.333333,445.111111,331.666667,372.666667,418.888889,743.888889,1104.111111,1240.111111,...,-73.887902,40.827521,-73.886393,0.095308,40.827136,-73.887147,2014,9,6,Sunday
1687,Westchester Avenue-East 167 Avenue-Home Street,396.333333,280.000000,209.333333,205.777778,368.333333,884.666667,1369.111111,1352.444444,1409.111111,...,-73.887902,40.827521,-73.886393,0.095308,40.827136,-73.887147,2014,9,6,Sunday
1688,White Plains Road-Westchester Avenue-Cross Bro...,406.111111,274.833333,191.777778,168.666667,194.388889,265.388889,517.222222,763.166667,828.722222,...,-73.862662,40.834334,-73.862952,0.104157,40.833587,-73.862807,2014,9,6,Sunday
1689,White Plains Road-Westchester Avenue-Cross Bro...,114.277778,70.111111,47.500000,42.833333,56.833333,91.388889,196.611111,279.944444,293.444444,...,-73.862662,40.834334,-73.862952,0.104157,40.833587,-73.862807,2014,9,6,Sunday
1690,Westchester Avenue-Eagle Avenue-Cauldwell Avenue,517.611111,348.916667,258.888889,238.638889,314.027778,599.861111,1022.972222,1195.583333,1263.027778,...,-73.911070,40.815940,-73.910164,0.047537,40.815959,-73.910617,2014,9,6,Sunday
1691,Westchester Avenue-Eagle Avenue-Cauldwell Avenue,191.222222,127.866667,90.244444,79.133333,107.200000,219.022222,494.444444,598.288889,616.111111,...,-73.911070,40.815940,-73.910164,0.047537,40.815959,-73.910617,2014,9,6,Sunday
1692,Winchester Boulevard-88 Avenue-88 Avenue,51.444444,39.666667,27.111111,26.444444,37.777778,60.444444,126.333333,205.333333,171.333333,...,-73.736493,40.730651,-73.736493,0.000000,40.730651,-73.736493,2014,9,6,Sunday
1693,Winchester Boulevard-88 Avenue-88 Avenue,295.666667,179.777778,141.611111,123.444444,190.166667,381.722222,650.111111,742.166667,816.222222,...,-73.736493,40.730651,-73.736493,0.000000,40.730651,-73.736493,2014,9,6,Sunday
1694,Union Turnpike-Hewlett Street-Langdale Street,761.111111,503.055556,380.222222,321.777778,390.388889,640.666667,1188.111111,1592.000000,1709.333333,...,-73.702553,40.752218,-73.702019,0.028556,40.752177,-73.702286,2014,9,6,Sunday
1695,Union Turnpike-Hewlett Street-Langdale Street,37.666667,20.222222,11.777778,6.333333,13.333333,32.555556,101.555556,226.888889,212.666667,...,-73.702553,40.752218,-73.702019,0.028556,40.752177,-73.702286,2014,9,6,Sunday
1696,Grand Concourse-153 Street-East 156 Street,24.777778,15.222222,7.888889,7.222222,12.000000,22.888889,52.111111,160.111111,121.777778,...,-73.925635,40.823497,-73.924524,0.172333,40.822321,-73.925079,2014,9,6,Sunday
1697,Grand Concourse-153 Street-East 156 Street,69.222222,47.055556,36.555556,30.500000,33.611111,54.222222,129.166667,272.444444,320.222222,...,-73.925635,40.823497,-73.924524,0.172333,40.822321,-73.925079,2014,9,6,Sunday
1698,3 Avenue-Senator Street-68 Street,57.222222,44.166667,31.277778,25.555556,27.222222,47.166667,94.277778,190.722222,211.333333,...,-74.025346,40.767197,-73.962470,9.574479,40.702075,-73.993908,2014,9,0,Monday
1699,3 Avenue-Senator Street-68 Street,43.611111,27.888889,19.388889,16.944444,25.666667,36.555556,70.000000,126.111111,164.722222,...,-74.025346,40.767197,-73.962470,9.574479,40.702075,-73.993908,2014,9,0,Monday
1700,5 Avenue-65 Street-Gowanus Expressway,156.222222,95.444444,60.888889,44.111111,47.777778,83.555556,221.333333,382.333333,378.000000,...,-73.970277,40.636801,-74.018969,9.409077,40.702415,-73.994623,2014,9,0,Monday
1701,5 Avenue-65 Street-Gowanus Expressway,105.777778,55.444444,33.777778,33.444444,89.444444,235.888889,390.222222,426.333333,457.000000,...,-73.970277,40.636801,-74.018969,9.409077,40.702415,-73.994623,2014,9,0,Monday
1702,7 Avenue-68 Street-67 Street,264.555556,167.333333,130.333333,115.166667,139.500000,209.166667,388.888889,549.944444,561.555556,...,-74.016689,40.633217,-74.016407,0.063082,40.632773,-74.016548,2014,9,0,Monday
1703,47 Avenue-190 Street-189 Street,66.388889,49.333333,29.166667,25.333333,25.666667,40.388889,116.833333,225.777778,268.777778,...,-73.789539,40.750919,-73.790438,0.049715,40.751033,-73.789988,2014,9,0,Monday
1704,47 Avenue-190 Street-189 Street,70.500000,48.000000,26.777778,20.722222,25.500000,44.333333,121.111111,249.055556,291.055556,...,-73.789539,40.750919,-73.790438,0.049715,40.751033,-73.789988,2014,9,0,Monday
1705,94 Avenue-Van Wyck Expressway-138 Place,261.722222,137.388889,94.055556,88.277778,127.333333,201.888889,406.111111,491.888889,569.277778,...,-73.808281,40.697576,-73.811564,0.767005,40.692160,-73.809922,2014,9,0,Monday
1706,94 Avenue-Van Wyck Expressway-138 Place,231.166667,149.722222,128.333333,79.222222,94.777778,168.333333,306.611111,525.888889,626.444444,...,-73.808281,40.697576,-73.811564,0.767005,40.692160,-73.809922,2014,9,0,Monday
1707,120 Avenue-191 Street-192 Street,263.666667,159.722222,105.722222,93.166667,116.055556,170.611111,328.444444,437.888889,518.500000,...,-73.758024,40.688022,-73.756890,0.066061,40.687815,-73.757457,2014,9,0,Monday
1708,120 Avenue-191 Street-192 Street,96.888889,61.166667,41.833333,39.000000,45.722222,99.444444,280.555556,258.388889,314.611111,...,-73.758024,40.688022,-73.756890,0.066061,40.687815,-73.757457,2014,9,0,Monday

In [17]:
temp_traffic = traffic_data_out.copy()

In [18]:
temp_traffic.columns

Index(['Segment Address', '12:00-1:00 AM', '1:00-2:00AM', '2:00-3:00AM',
       '3:00-4:00AM', '4:00-5:00AM', '5:00-6:00AM', '6:00-7:00AM',
       '7:00-8:00AM', '8:00-9:00AM', '9:00-10:00AM', '10:00-11:00AM',
       '11:00-12:00PM', '12:00-1:00PM', '1:00-2:00PM', '2:00-3:00PM',
       '3:00-4:00PM', '4:00-5:00PM', '5:00-6:00PM', '6:00-7:00PM',
       '7:00-8:00PM', '8:00-9:00PM', '9:00-10:00PM', '10:00-11:00PM',
       '11:00-12:00AM', 'ID', 'Segment ID', 'Roadway Name', 'From', 'To',
       'Date', 'Start Intersection', 'End Intersection', 'Lat Start',
       'Lng Start', 'Lat End', 'Lng End', 'distance', 'Center Lat',
       'Center Lng', 'year', 'month', 'weekday', 'day name'],
      dtype='object')

In [19]:
columns_to_keep = ['Segment Address', 'ID', 'Segment ID', 'Roadway Name', 'From', 'To',
       'Date', 'Start Intersection', 'End Intersection', 'Lat Start',
       'Lng Start', 'Lat End', 'Lng End', 'distance', 'Center Lat',
       'Center Lng', 'year', 'month', 'weekday', 'day name']

In [20]:
temp_traffic = temp_traffic.melt(id_vars=columns_to_keep, var_name='hour of day')

In [21]:
def convert_time_interval(df):
    
    time_day = []
    
    for i, row in df.iterrows():
        am_pm = row['hour of day'].split(':')[2][-2:]
        hour = row['hour of day'].split(':')[0]
        
        if am_pm == 'AM' and hour == '11':
            time_of_day = 23
        elif am_pm == 'PM' and hour == '11':
            time_of_day = 11
        elif am_pm == 'AM' and hour == '12':
            time_of_day = 0
        elif am_pm == 'PM' and hour == '12':
            time_of_day = hour
        elif am_pm == 'PM':
            time_of_day = int(hour) + 12
        else:
            time_of_day = hour
            
        time_day.append(time_of_day)
    
    df["time of day"] = time_day

In [22]:
convert_time_interval(temp_traffic)

In [23]:
temp_traffic['month'].unique()

array([ 9, 11,  2, 10], dtype=int64)

In [24]:
temp_traffic['time of day'].unique()

array([0, '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 11, '12', 13,
       14, 15, 16, 17, 18, 19, 20, 21, 22, 23], dtype=object)

In [25]:
temp_traffic.head()

,Segment Address,ID,Segment ID,Roadway Name,From,To,Date,Start Intersection,End Intersection,Lat Start,...,distance,Center Lat,Center Lng,year,month,weekday,day name,hour of day,value,time of day
0,3 Avenue-East 154 Street-East 155 Street,2,70376,3 Avenue,East 154 Street,East 155 Street,09/13/2014,3 Avenue East 154 Street,3 Avenue East 155 Street,40.818951,...,0.048887,40.819247,-73.913783,2014,9,5,Saturday,12:00-1:00 AM,979.111111,0
1,3 Avenue-East 155 Street-East 154 Street,2,70376,3 Avenue,East 155 Street,East 154 Street,09/13/2014,3 Avenue East 155 Street,3 Avenue East 154 Street,40.819544,...,0.048887,40.819247,-73.913783,2014,9,5,Saturday,12:00-1:00 AM,679.000000,0
2,Bedford Park Boulevard-Grand Concourse-Valenti...,56,176365,Bedford Park Boulevard,Grand Concourse,Valentine Avenue,09/13/2014,Bedford Park Boulevard Grand Concourse,Bedford Park Boulevard Valentine Avenue,40.872153,...,0.081017,40.871725,-73.887540,2014,9,5,Saturday,12:00-1:00 AM,867.000000,0
3,Bedford Park Boulevard-Grand Concourse-Valenti...,56,176365,Bedford Park Boulevard,Grand Concourse,Valentine Avenue,09/13/2014,Bedford Park Boulevard Grand Concourse,Bedford Park Boulevard Valentine Avenue,40.872153,...,0.081017,40.871725,-73.887540,2014,9,5,Saturday,12:00-1:00 AM,1331.555556,0
4,Broadway-West 242 Street-240 Street,62,147673,Broadway,West 242 Street,240 Street,09/13/2014,Broadway West 242 Street,Broadway 240 Street,40.889463,...,0.214140,40.887996,-73.899020,2014,9,5,Saturday,12:00-1:00 AM,965.666667,0

In [26]:
grouped_traffic = temp_traffic.groupby(['Segment Address','Segment ID','Center Lat','Center Lng','time of day']).agg({'value':'mean'})

In [27]:
grouped_traffic.reset_index(inplace = True)

In [28]:
grouped_traffic.head()

,Segment Address,Segment ID,Center Lat,Center Lng,time of day,value
0,110 AVENUE-155 STREET-156 STREET,60160,40.691026,-73.794379,0,498.027778
1,110 AVENUE-155 STREET-156 STREET,60160,40.691026,-73.794379,11,814.361111
2,110 AVENUE-155 STREET-156 STREET,60160,40.691026,-73.794379,13,835.972222
3,110 AVENUE-155 STREET-156 STREET,60160,40.691026,-73.794379,14,871.500000
4,110 AVENUE-155 STREET-156 STREET,60160,40.691026,-73.794379,15,939.000000

In [29]:
traffic_data_out['Segment Address'].nunique()

195

In [30]:
traffic_data_out['Date'].nunique()

21

## Positive Sample Joining

In [55]:
accident_data = pd.read_csv('Data/NY_Accidents_June20.csv')
accident_data.head()

,Unnamed: 0,ID,Source,TMC,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,Distance(mi),...,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight,acc_year,acc_month,acc_hr_day,new_date,day_name
0,194406,A-194408,MapQuest,201.0,2,2016-12-01 08:21:11,2016-12-01 08:50:48,40.770107,-73.957397,0.01,...,False,Day,Day,Day,Day,2016,12,8,2016-12-01,Thursday
1,194420,A-194422,MapQuest,241.0,3,2016-12-01 08:49:35,2016-12-01 09:19:14,40.849579,-73.942314,1.13,...,False,Day,Day,Day,Day,2016,12,8,2016-12-01,Thursday
2,194473,A-194475,MapQuest,245.0,2,2016-12-01 12:08:26,2016-12-01 12:37:55,40.748028,-73.968170,0.01,...,False,Day,Day,Day,Day,2016,12,12,2016-12-01,Thursday
3,194538,A-194540,MapQuest,201.0,2,2016-12-02 05:19:11,2016-12-02 05:49:02,40.761723,-73.982803,0.01,...,False,Night,Night,Night,Night,2016,12,5,2016-12-02,Friday
4,194556,A-194558,MapQuest-Bing,241.0,2,2016-12-02 07:09:04,2016-12-02 07:38:36,40.782818,-73.943871,0.01,...,False,Day,Day,Day,Day,2016,12,7,2016-12-02,Friday

In [56]:
accident_data['acc_hr_day'].unique()

array([ 8, 12,  5,  7, 11, 18,  6, 13, 15, 20, 10, 16,  9, 19, 22, 14, 17,
        2,  4, 21,  0,  1, 23,  3], dtype=int64)

In [57]:
from scipy import spatial

In [58]:
def find_closest_node(accident_row, df):
    '''
    accident_row is one row containing accident data with ID, Start_Lat and Start_Lng
    df is the dataframe containing traffic flow with Center Lat and Center Lng
    df schema:
    - Segment Address
    - Center Lat
    - Center Lng
    '''
    
    df_coordinates = df[['Center Lat', 'Center Lng']]
    
    node_tree = spatial.KDTree(df_coordinates)

    distance_to_nearest_node, nearest_node_index = node_tree.query(node_row[['Start_Lat', 'Start_Lng']])
    nearest_node_ID = df.iloc[nearest_node_index][0]

    return nearest_node_ID, distance_to_nearest_node

In [59]:
column_name = ['ID','Start_Lat','Start_Lng']

nearest_id = []
nearest_id_distance = []

for row in accident_data.iterrows():
    node_row = row[1].get(column_name)
    flow_id, distance_to_grid_node = find_closest_node(node_row, traffic_data_out)
    nearest_id.append(flow_id)
    nearest_id_distance.append(distance_to_grid_node)

In [60]:
accident_data['Traffic Flow ID'] = nearest_id
accident_data['Distance to Traffic Flow']=nearest_id_distance

In [61]:
accident_data['Flow ID - hour'] = accident_data.apply(lambda x: x['Traffic Flow ID'] + '-' + str(x['acc_hr_day']) \
                                                      ,axis = 1 )

In [62]:
accident_data.head()

,Unnamed: 0,ID,Source,TMC,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,Distance(mi),...,Nautical_Twilight,Astronomical_Twilight,acc_year,acc_month,acc_hr_day,new_date,day_name,Traffic Flow ID,Distance to Traffic Flow,Flow ID - hour
0,194406,A-194408,MapQuest,201.0,2,2016-12-01 08:21:11,2016-12-01 08:50:48,40.770107,-73.957397,0.01,...,Day,Day,2016,12,8,2016-12-01,Thursday,79 Street Transverse-5 Avenue-East Drive,0.011682,79 Street Transverse-5 Avenue-East Drive-8
1,194420,A-194422,MapQuest,241.0,3,2016-12-01 08:49:35,2016-12-01 09:19:14,40.849579,-73.942314,1.13,...,Day,Day,2016,12,8,2016-12-01,Thursday,Wadsworth Avenue-West 176 Street-West 175 Street,0.005776,Wadsworth Avenue-West 176 Street-West 175 Stre...
2,194473,A-194475,MapQuest,245.0,2,2016-12-01 12:08:26,2016-12-01 12:37:55,40.748028,-73.968170,0.01,...,Day,Day,2016,12,12,2016-12-01,Thursday,BQE-59 Place-59 Street,0.007049,BQE-59 Place-59 Street-12
3,194538,A-194540,MapQuest,201.0,2,2016-12-02 05:19:11,2016-12-02 05:49:02,40.761723,-73.982803,0.01,...,Night,Night,2016,12,5,2016-12-02,Friday,BQE-59 Place-59 Street,0.014843,BQE-59 Place-59 Street-5
4,194556,A-194558,MapQuest-Bing,241.0,2,2016-12-02 07:09:04,2016-12-02 07:38:36,40.782818,-73.943871,0.01,...,Day,Day,2016,12,7,2016-12-02,Friday,Park Avenue-East 99 Street-East 100 Street,0.009235,Park Avenue-East 99 Street-East 100 Street-7

In [63]:
grouped_traffic['Flow ID - hour'] = grouped_traffic.apply(lambda x: x['Segment Address'] + '-' + str(x['time of day']) ,axis = 1 )

In [64]:
traffic_accident_merged = accident_data.merge(grouped_traffic, how = 'left', left_on = 'Flow ID - hour', 
                                  right_on = 'Flow ID - hour')
traffic_accident_merged.head()

,Unnamed: 0,ID,Source,TMC,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,Distance(mi),...,day_name,Traffic Flow ID,Distance to Traffic Flow,Flow ID - hour,Segment Address,Segment ID,Center Lat,Center Lng,time of day,value
0,194406,A-194408,MapQuest,201.0,2,2016-12-01 08:21:11,2016-12-01 08:50:48,40.770107,-73.957397,0.01,...,Thursday,79 Street Transverse-5 Avenue-East Drive,0.011682,79 Street Transverse-5 Avenue-East Drive-8,79 Street Transverse-5 Avenue-East Drive,115284,40.777947,-73.966057,8,687.027778
1,194420,A-194422,MapQuest,241.0,3,2016-12-01 08:49:35,2016-12-01 09:19:14,40.849579,-73.942314,1.13,...,Thursday,Wadsworth Avenue-West 176 Street-West 175 Street,0.005776,Wadsworth Avenue-West 176 Street-West 175 Stre...,Wadsworth Avenue-West 176 Street-West 175 Street,70947,40.846291,-73.937565,8,1716.117284
2,194473,A-194475,MapQuest,245.0,2,2016-12-01 12:08:26,2016-12-01 12:37:55,40.748028,-73.968170,0.01,...,Thursday,BQE-59 Place-59 Street,0.007049,BQE-59 Place-59 Street-12,BQE-59 Place-59 Street,144331,40.749004,-73.975152,12,490.000000
3,194538,A-194540,MapQuest,201.0,2,2016-12-02 05:19:11,2016-12-02 05:49:02,40.761723,-73.982803,0.01,...,Friday,BQE-59 Place-59 Street,0.014843,BQE-59 Place-59 Street-5,BQE-59 Place-59 Street,144331,40.749004,-73.975152,5,99.111111
4,194556,A-194558,MapQuest-Bing,241.0,2,2016-12-02 07:09:04,2016-12-02 07:38:36,40.782818,-73.943871,0.01,...,Friday,Park Avenue-East 99 Street-East 100 Street,0.009235,Park Avenue-East 99 Street-East 100 Street-7,Park Avenue-East 99 Street-East 100 Street,158778,40.788818,-73.950892,7,479.740741

In [65]:
traffic_accident_merged.to_csv('Data/NY_Accidents.csv')

## Negative Sample Joining

In [66]:
neg_accident_data = pd.read_csv('Data/NY_Negatives_June20.csv')
neg_accident_data.head()

,Unnamed: 0,ID,Source,TMC,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,Distance(mi),...,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight,acc_year,acc_month,acc_hr_day,new_date,day_name
0,478976,A-478982,MapQuest,201.0,2,2016-12-01 08:21:11,2016-12-01 08:50:48,40.850063,-73.944794,1.97,...,False,Day,Day,Day,Day,2016,12,8,2016-12-01,Thursday
1,589230,A-589238,MapQuest,201.0,2,2016-12-01 08:21:11,2016-12-01 08:50:48,40.746658,-73.969345,0.00,...,False,Day,Day,Day,Day,2016,12,8,2016-12-01,Thursday
2,2624326,A-2624367,Bing,NaN,2,2016-12-01 08:21:11,2016-12-01 08:50:48,40.793840,-73.931880,0.06,...,False,Day,Day,Day,Day,2016,12,8,2016-12-01,Thursday
3,2425131,A-2425172,MapQuest,201.0,3,2016-12-01 08:21:11,2016-12-01 08:50:48,40.850067,-73.944817,1.65,...,False,Day,Day,Day,Day,2016,12,8,2016-12-01,Thursday
4,1595383,A-1595416,MapQuest,201.0,2,2016-12-01 08:21:11,2016-12-01 08:50:48,40.782791,-73.957397,0.00,...,False,Day,Day,Day,Day,2016,12,8,2016-12-01,Thursday

In [67]:
column_name = ['ID','Start_Lat','Start_Lng']

nearest_id = []
nearest_id_distance = []

for row in neg_accident_data.iterrows():
    node_row = row[1].get(column_name)
    flow_id, distance_to_grid_node = find_closest_node(node_row, traffic_data_out)
    nearest_id.append(flow_id)
    nearest_id_distance.append(distance_to_grid_node)

In [68]:
neg_accident_data['Traffic Flow ID'] = nearest_id
neg_accident_data['Distance to Traffic Flow']=nearest_id_distance

In [69]:
neg_accident_data['Flow ID - hour'] = neg_accident_data.apply(lambda x: x['Traffic Flow ID'] + '-' + str(x['acc_hr_day']) \
                                                      ,axis = 1 )

In [70]:
traffic_neg_accident_merged = neg_accident_data.merge(grouped_traffic, how = 'left', left_on = 'Flow ID - hour', 
                                  right_on = 'Flow ID - hour')
traffic_neg_accident_merged.head()

,Unnamed: 0,ID,Source,TMC,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,Distance(mi),...,day_name,Traffic Flow ID,Distance to Traffic Flow,Flow ID - hour,Segment Address,Segment ID,Center Lat,Center Lng,time of day,value
0,478976,A-478982,MapQuest,201.0,2,2016-12-01 08:21:11,2016-12-01 08:50:48,40.850063,-73.944794,1.97,...,Thursday,Wadsworth Avenue-West 176 Street-West 175 Street,0.008154,Wadsworth Avenue-West 176 Street-West 175 Stre...,Wadsworth Avenue-West 176 Street-West 175 Street,70947,40.846291,-73.937565,8,1716.117284
1,589230,A-589238,MapQuest,201.0,2,2016-12-01 08:21:11,2016-12-01 08:50:48,40.746658,-73.969345,0.00,...,Thursday,BQE-59 Place-59 Street,0.006263,BQE-59 Place-59 Street-8,BQE-59 Place-59 Street,144331,40.749004,-73.975152,8,485.666667
2,2624326,A-2624367,Bing,NaN,2,2016-12-01 08:21:11,2016-12-01 08:50:48,40.793840,-73.931880,0.06,...,Thursday,Madison Avenue-East 121 Street-East 122 Street,0.014215,Madison Avenue-East 121 Street-East 122 Street-8,Madison Avenue-East 121 Street-East 122 Street,69057,40.803502,-73.942307,8,479.709877
3,2425131,A-2425172,MapQuest,201.0,3,2016-12-01 08:21:11,2016-12-01 08:50:48,40.850067,-73.944817,1.65,...,Thursday,Wadsworth Avenue-West 176 Street-West 175 Street,0.008176,Wadsworth Avenue-West 176 Street-West 175 Stre...,Wadsworth Avenue-West 176 Street-West 175 Street,70947,40.846291,-73.937565,8,1716.117284
4,1595383,A-1595416,MapQuest,201.0,2,2016-12-01 08:21:11,2016-12-01 08:50:48,40.782791,-73.957397,0.00,...,Thursday,86 Street Transverse-5 Avenue-East Drive,0.004498,86 Street Transverse-5 Avenue-East Drive-8,86 Street Transverse-5 Avenue-East Drive,37480,40.782334,-73.961872,8,1126.000000

In [71]:
traffic_neg_accident_merged.to_csv('Data/NY_Negatives.csv')